// <auto-generated />
using System;
using IS220_WebApplication.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IS220_WebApplication.Initial
{
    [DbContext(typeof(MyDbContext))]
    partial class MyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("CategoryGame", b =>
                {
                    b.Property<uint>("Category")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("Game")
                        .HasColumnType("int unsigned");

                    b.HasKey("Category", "Game");

                    b.ToTable("CategoryGame");
                });

            modelBuilder.Entity("GameCategory", b =>
                {
                    b.Property<uint>("Game")
                        .HasColumnType("int(10) unsigned")
                        .HasColumnName("game");

                    b.Property<uint>("Category")
                        .HasColumnType("int(10) unsigned")
                        .HasColumnName("category");

                    b.HasKey("Game", "Category")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Category" }, "FK_GC_Category");

                    b.ToTable("game_category", (string)null);
                });

            modelBuilder.Entity("IS220_WebApplication.Models.Category", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(10) unsigned")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("category");
                });

            modelBuilder.Entity("IS220_WebApplication.Models.Developer", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(10) unsigned")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("developer");
                });

            modelBuilder.Entity("IS220_WebApplication.Models.Efmigrationshistory", b =>
                {
                    b.Property<string>("MigrationId")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("ProductVersion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.HasKey("MigrationId")
                        .HasName("PRIMARY");

                    b.ToTable("__efmigrationshistory");
                });

            modelBuilder.Entity("IS220_WebApplication.Models.Game", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(10) unsigned")
                        .HasColumnName("id");

                    b.Property<bool?>("Active")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("active")
                        .HasDefaultValueSql("'1'");

                    b.Property<string>("Description")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasColumnName("description")
                        .HasDefaultValueSql("'NULL'");

                    b.Property<uint>("Developer")
                        .HasColumnType("int(10) unsigned")
                        .HasColumnName("developer");

                    b.Property<string>("DownloadLink")
                        .IsRequired()
                        .HasColumnType("tinytext")
                        .HasColumnName("downloadLink");

                    b.Property<string>("ImgPath")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinytext")
                        .HasColumnName("imgPath")
                        .HasDefaultValueSql("'NULL'");

                    b.Property<decimal>("Price")
                        .HasPrecision(10)
                        .HasColumnType("decimal(10,0)")
                        .HasColumnName("price");

                    b.Property<uint>("Publisher")
                        .HasColumnType("int(10) unsigned")
                        .HasColumnName("publisher");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("date")
                        .HasColumnName("releaseDate");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("title");

                    b.Property<int>("Type")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(1)")
                        .HasColumnName("type")
                        .HasDefaultValueSql("'1'");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Developer" }, "FK_Game_Developer");

                    b.HasIndex(new[] { "Publisher" }, "FK_Game_Publisher");

                    b.ToTable("game");
                });

            modelBuilder.Entity("IS220_WebApplication.Models.GameOwned", b =>
                {
                    b.Property<uint>("GameId")
                        .HasColumnType("int(10) unsigned")
                        .HasColumnName("gameID");

                    b.Property<uint>("UserId")
                        .HasColumnType("int(10) unsigned")
                        .HasColumnName("userID");

                    b.HasIndex(new[] { "GameId" }, "FK_GameOwner_Game");

                    b.HasIndex(new[] { "UserId" }, "FK_GameOwner_User");

                    b.ToTable("game_owned");
                });

            modelBuilder.Entity("IS220_WebApplication.Models.Publisher", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(10) unsigned")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("publisher");
                });

            modelBuilder.Entity("IS220_WebApplication.Models.Transaction", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(10) unsigned")
                        .HasColumnName("id");

                    b.Property<DateTime>("Date")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("date")
                        .HasDefaultValueSql("'current_timestamp()'");

                    b.Property<uint>("TransInfoId")
                        .HasColumnType("int(11) unsigned")
                        .HasColumnName("transInfoID");

                    b.Property<uint>("UserId")
                        .HasColumnType("int(10) unsigned")
                        .HasColumnName("userID");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "TransInfoId" }, "FK_Info_Trans");

                    b.HasIndex(new[] { "UserId" }, "FK_User_Trans");

                    b.ToTable("transaction");
                });

            modelBuilder.Entity("IS220_WebApplication.Models.TransactionInfomation", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11) unsigned")
                        .HasColumnName("id");

                    b.Property<int>("Amount")
                        .HasColumnType("int(11)")
                        .HasColumnName("amount");

                    b.Property<uint?>("GameId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11) unsigned")
                        .HasColumnName("gameID")
                        .HasDefaultValueSql("'NULL'");

                    b.Property<uint>("TypeId")
                        .HasColumnType("int(11) unsigned")
                        .HasColumnName("typeID");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "GameId" }, "FK_Game_Trans");

                    b.HasIndex(new[] { "TypeId" }, "Fk_Type_Trans");

                    b.ToTable("transaction_infomation");
                });

            modelBuilder.Entity("IS220_WebApplication.Models.TransactionType", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(10) unsigned")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("transaction_type");
                });

            modelBuilder.Entity("IS220_WebApplication.Models.User", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(10) unsigned")
                        .HasColumnName("id");

                    b.Property<DateTime?>("Birth")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasColumnName("birth")
                        .HasDefaultValueSql("'NULL'");

                    b.Property<int>("Cash")
                        .HasColumnType("int(11)")
                        .HasColumnName("cash");

                    b.Property<DateTime>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created")
                        .HasDefaultValueSql("'current_timestamp()'");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("firstName")
                        .HasDefaultValueSql("'NULL'");

                    b.Property<string>("LastName")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("lastName")
                        .HasDefaultValueSql("'NULL'");

                    b.Property<DateTime?>("Modified")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime")
                        .HasColumnName("modified")
                        .HasDefaultValueSql("'NULL'");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.Property<string>("Phone")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("phone")
                        .HasDefaultValueSql("'NULL'");

                    b.Property<sbyte>("Role")
                        .HasColumnType("tinyint(4)")
                        .HasColumnName("role");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(1)")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'1'");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Email" }, "email")
                        .IsUnique();

                    b.HasIndex(new[] { "Username" }, "username")
                        .IsUnique();

                    b.ToTable("user");
                });

            modelBuilder.Entity("GameCategory", b =>
                {
                    b.HasOne("IS220_WebApplication.Models.Category", null)
                        .WithMany()
                        .HasForeignKey("Category")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_GC_Category");

                    b.HasOne("IS220_WebApplication.Models.Game", null)
                        .WithMany()
                        .HasForeignKey("Game")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_GC_Game");
                });

            modelBuilder.Entity("IS220_WebApplication.Models.Game", b =>
                {
                    b.HasOne("IS220_WebApplication.Models.Developer", "DeveloperNavigation")
                        .WithMany("Games")
                        .HasForeignKey("Developer")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Game_Developer");

                    b.HasOne("IS220_WebApplication.Models.Publisher", "PublisherNavigation")
                        .WithMany("Games")
                        .HasForeignKey("Publisher")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Game_Publisher");

                    b.Navigation("DeveloperNavigation");

                    b.Navigation("PublisherNavigation");
                });

            modelBuilder.Entity("IS220_WebApplication.Models.GameOwned", b =>
                {
                    b.HasOne("IS220_WebApplication.Models.Game", "Game")
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_GameOwner_Game");

                    b.HasOne("IS220_WebApplication.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_GameOwner_User");

                    b.Navigation("Game");

                    b.Navigation("User");
                });

            modelBuilder.Entity("IS220_WebApplication.Models.Transaction", b =>
                {
                    b.HasOne("IS220_WebApplication.Models.TransactionInfomation", "TransInfo")
                        .WithMany("Transactions")
                        .HasForeignKey("TransInfoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Info_Trans");

                    b.HasOne("IS220_WebApplication.Models.User", "User")
                        .WithMany("Transactions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_User_Trans");

                    b.Navigation("TransInfo");

                    b.Navigation("User");
                });

            modelBuilder.Entity("IS220_WebApplication.Models.TransactionInfomation", b =>
                {
                    b.HasOne("IS220_WebApplication.Models.Game", "Game")
                        .WithMany("TransactionInfomations")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_Game_Trans");

                    b.HasOne("IS220_WebApplication.Models.TransactionType", "Type")
                        .WithMany("TransactionInfomations")
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("Fk_Type_Trans");

                    b.Navigation("Game");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("IS220_WebApplication.Models.Developer", b =>
                {
                    b.Navigation("Games");
                });

            modelBuilder.Entity("IS220_WebApplication.Models.Game", b =>
                {
                    b.Navigation("TransactionInfomations");
                });

            modelBuilder.Entity("IS220_WebApplication.Models.Publisher", b =>
                {
                    b.Navigation("Games");
                });

            modelBuilder.Entity("IS220_WebApplication.Models.TransactionInfomation", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("IS220_WebApplication.Models.TransactionType", b =>
                {
                    b.Navigation("TransactionInfomations");
                });

            modelBuilder.Entity("IS220_WebApplication.Models.User", b =>
                {
                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
